services:
    db_rentacar:
        image: postgres
        container_name: db_rentacar
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=dockerpass
            - POSTGRES_DB=rent-an-auto
        volumes:
            - pgdata:/data/postgres

volumes:
    pgdata:
        driver: local
